apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv-default
  labels:
    pv: cephfs-pv-default
  namespace: default
spec:
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 172.0.7.241:6789
      - 172.0.7.242:6789
      - 172.0.7.243:6789
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
