kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-pvc-default
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  selector:
    matchLabels:
      pv: cephfs-pv-default
